[build]
  # tell Netlify to cd into the frontend folder first
  base = "../frontend"

  # how to build your React app
  command = "npm run build"

  # after building, publish the build folder
  publish = "build"
